### PR TITLE
Add installation instructions to readme.

### PR DESCRIPTION
**Pull request by kahaaga**

### CODE REVIEW

**Comment by Datseris** [comment]
Oh damn, wait, was this supposed to have more things? Well, sorry, please open another PR :D

**Comment by Datseris** [comment]
btw @kahaaga just letting you know that I don't agree with some of the suggestions of the review for changing the documentation. Only with adding installation instructions I agree. We have a dedicated page on what are surrogates, there is no point to repeat the information in the opening paragraphs of the docs. A good documentation is the one that has the least amount of repetition.

**Comment by Datseris** [comment]
we also has countless examples, adding yet another in the opening page is once again unecessary repetition.

**Comment by kahaaga** [comment]
> Oh damn, wait, was this supposed to have more things? Well, sorry, please open another PR :D

I don't think it actually needs to. Everything that should be included is in the docs for this PR.

> just letting you know that I don't agree with some of the suggestions of the review for changing the documentation. Only with adding installation instructions I agree. We have a dedicated page on what are surrogates, there is no point to repeat the information in the opening paragraphs of the docs. A good documentation is the one that has the least amount of repetition.
> we also has countless examples, adding yet another in the opening page is once again unecessary repetition.

I agree, and the reviewers potentially might too once they look at the updated docs. 

I'll just point the reviewers to the updated documentation and see if they like that better. Any further suggestions they have on *that* documentation I'll be happy to consider.

**Comment by kahaaga** [comment]
> I don't think it actually needs to. Everything that should be included is in the docs for this PR.

... and by that I mean what is currently merged on master.

> Only with adding installation instructions I agree

Yes, now the installation instructions are both in the main repo readme, and in the documentation pages.

**Pull request merged**
