### PR TITLE
Export fill_surrogate_test!

### PR DESCRIPTION
**Pull request by Datseris**
I hope the title is self-explanatory!

### CODE REVIEW

**Comment by Datseris** [comment]
what the hell is this test failure that I can barely understand :D

**Comment by kahaaga** [comment]
> turns out, you cannot put docstrings before @inbounds. 

Nice to know :D

**Comment by kahaaga** [comment]
There's a weird test error. Not sure why this occurs. Do the docs build locally?

**Comment by kahaaga** [comment]
The doc errors are not as cryptic, but there's still a few points to fix:

Skjermbilde 2024-01-20 kl  17 23 22

**Comment by kahaaga** [comment]
Screenshot 2024-06-04 at 12 52 06

Is it on purpose that this figure isn't displayed in the generated docs, @Datseris ?

**Pull request merged**
