### PR TITLE
Adding more padding modes to RandomCascade

### PR DESCRIPTION
**Pull request by sathvikbhagavan**
Fixes: #120

### CODE REVIEW

**Comment by Datseris** [comment]
Could we add a test for the other two options as well please?

**Comment by Datseris** [comment]
BTW @sathvikbhagavan I've noticed that you work on JuliaHub, a website I use all the time to register packages. Is your interest in TimeseriesSurrogates.jl by any chance related to the JuliaHub project...?

**Comment by sathvikbhagavan** [comment]
>a website I use all the time to register packages.

That's great to hear!

>Is your interest in TimeseriesSurrogates.jl by any chance related to the JuliaHub project...?

No, the work I do at JuliaHub is unrelated to this. Trying to contribute to open source packages :)

**Comment by Datseris** [comment]
Thanks, LGTM!

**Pull request merged**
