### PR TITLE
Add `SurrogateTest` type for convenient hypothesis testing

### LINKED ISSUE #142: An API for significance
We are developing [TransitionIndicators.jl](https://github.com/JuliaDynamics/TransitionIndicators.jl). There we use this surrogate package to test for significance. I coded the code below to bring simplicity in how we test for significance. But then I saw that CausalityTools.jl also has significance tests with surrogates and defines and exports types about it.

In the `SurrogateTest` of CausalityTools.jl it is not clear to me how independence is tested. In the end of the day you need to provide a true or false, which means you need to compare the true value with the surrogate distribution values. How do you do that precisely?

In any case, see the code above, which can be a basis on how to claim "significance" (in the sense that a real value is well outside the distribution of surrogates). Ideally, we won't duplicate code here and in CausalityTools.jl and we can define shared code in TimeseriesSurrogates.jl

```julia
using Statistics: quantile

"""
    SignificanceTest
Abstract type encompassing ways to test for significance in the function
[`significant`](@ref). Using its subtypes, the _real value_
derived from input data
is compared with the _distribution of the surrogate values_.
Subtypes:
- [`Quantile`](@ref)
- [`Sigma`](@ref)
"""
abstract type Significance end

"""
    significant(v::Real, s_vals::AbstractVector, q::Significance) → true/false
Return `true` if the value `v` is significant when compared to distribution of
surrogate values `s_vals` according to the criterion `q` (see [`SignificanceTest`](@ref)).
If not significant, return `false`.
If given `q::Real`, then [`Quantile`](@ref) is used.
"""
significant(v, s_vals, q::Real) = significant(v, s_vals, Quantile(q))

"""
    Quantile(q = 0.99, dir::Symbol = :updown) <: SignificanceTest
Significance is claimed by comparing the real value `v` with the `q`-th quantile of the
surrogate distribution. Three possibilities are provided depending on `dir`:
- `dir = :updown`: Significance is claimed if `v` is more than the `q`-th or is
  less than the `1-q`-th quantile
- `dir = :up`: if `v` is more than `q`-th
- `dir = :down`: if `v` is less than `1-q`-th
"""
struct Quantile <: Significance
    q::Float64
    dir::Symbol
end
Quantile(q = 0.99, dir = :updown) = Quantile(q, dir)

function significant(val, s_vals, quant::Quantile)
    q = quant.q
    if quant.dir == :updown
        low, high = quantile(s_vals, (1-q, q))
        return val < low || val > high
    elseif quant.dir == :up
        high = quantile(s_vals, q)
        return val > high
    elseif quant.dir == :down
        low = quantile(s_vals, 1-q)
        return val < low
    else
        error()
    end
end




"""
    Sigma(n::Real = 3, dir::Symbol = :updown) <: SignificanceTest
Significance is claimed by comparing the real value `v` with the
mean `μ` and standard deviation `σ` of the surrogate distribution.
Three possibilities are provided depending on `dir`:
- `dir = :updown`: significance is claimed if `v` is more than `μ + n*σ` or less than
  `μ - n*σ`.
- `dir = :up`: if `v` is more than `μ + n*σ`
- `dir = :down`: if `v` is less than `μ - n*σ`
"""
struct Sigma <: Significance
    n::Float64
    dir::Symbol
end
Sigma(n = 3, dir = :updown) = Sigma(n, dir)

using StatsBase: mean_and_std

function significant(val, s_vals, sigma::Sigma)
    n = sigma.n
    μ, σ = mean_and_std(s_vals)
    low, high = μ - n*σ, μ + n*σ
    if sigma.dir == :updown
        return val < low || val > high
    elseif sigma.dir == :up
        return val > high
    elseif sigma.dir == :down
        return val < low
    else
        error()
    end
end
```

### PR DESCRIPTION
**Pull request by Datseris**
Closes #142 .

At the moment the new version of StatsAPI isn't released so we cannot really extend its method.

### CODE REVIEW

**Comment by kahaaga** [comment]
One of these docstrings should contain an example on how to provide `f`. Alternatively, there should be an example use case where the user defines `f` for some relevant measures.

**Comment by kahaaga** [comment]
Could you also please not merge this until I've version-locked CausalityTools, so that there is no conflict between `SurrogateTest` here and `CausalityTools.SurrogateTest`? I can merge this PR and tag a new version of TimeseriesSurrogates.jl immediately when the version-lock is in place.

**Comment by Datseris** [comment]
I'm writing a full example in the docs now

**Comment by Datseris** [comment]
I added the example. Todo: tests and [pretty prinitng

**Comment by Datseris** [comment]
Okay this is good to go. Feel free to merge once you are ready. We shouldn't wait for hypothesis tests and stats API to publish releases. Once they publish a release where hypothesis test uses the `pvalue` from StatsAPI, then we can just tag `2.3` that extends the same function.

**Comment by kahaaga** [comment]
> Okay this is good to go. Feel free to merge once you are ready. We shouldn't wait for hypothesis tests and stats API to publish releases. Once they publish a release where hypothesis test uses the pvalue from StatsAPI, then we can just tag 2.3 that extends the same function.

Excellent! Thanks for your effort. 

I'll try to do the the `CausalityTools.SurrogateTest` rename today, so will hopefully merge this tonight.

**Comment by kahaaga** [comment]
This also closes #143.

**Pull request merged**
