### PR TITLE
Move docs to makie, fix docs

### LINKED ISSUE #91: Error when generating docs locally
@Datseris I just got the following error message when building the docs locally, in a fresh session. It seems to be related to theme compiling. Maybe this is related to why the docs have been taking > 1.5 hours to run in GitHub actions the past few days. 

Have you seen this error before? 

```Julia
 include("docs/make.jl")
ERROR: LoadError: UndefVarError: libsass_so not defined
Stacktrace:
 [1] sass_make_file_context(filename::String)
   @ Sass ~/.julia/packages/Sass/K4Tzw/src/context.jl:16
 [2] compile_file(filename::String; input_path::String, source_map_file::Nothing, kwargs::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:output_path, :include_path), Tuple{String, String}}})
   @ Sass ~/.julia/packages/Sass/K4Tzw/src/julian_api.jl:53
 [3] #compile_file#2
   @ ~/.julia/packages/Sass/K4Tzw/src/julian_api.jl:85 [inlined]
 [4] compile(src::String, dst::String)
   @ DocumenterTools.Themes ~/.julia/packages/DocumenterTools/m8nQ0/src/Themes.jl:50
 [5] top-level scope
   @ ~/Code/Repos/TimeseriesSurrogates.jl/docs/make.jl:29
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [7] top-level scope
   @ REPL[4]:1
in expression starting at [....]/TimeseriesSurrogates.jl/docs/make.jl:29
```

### PR DESCRIPTION
**Pull request by Datseris**
Closes #91

### CODE REVIEW

**Comment by kahaaga** [comment]
> where does the function interp come from, and what does it do? I doesn't come from either StatsBase or DSP.

@datseris It's just a simple wrapper around Interpolations.jl's `interpolate` with a gridded linear approach. The code is located in `src/utils/interpolation.jl`.

**Comment by Datseris** [comment]
Docs would be here but they obviously don't work and I have to fix them: https://juliadynamics.github.io/TimeseriesSurrogates.jl/previews/PR92/ 

@kahaaga I've dropped the interpolation entirely, it isn't that necessary

**Comment by Datseris** [comment]
@kahaaga we have a _huge_ problem. Something is going very wrong. I'm running the docs and one codeblock is taking up so much processing power and memory that it collapses my computer. I can't see which one it is because I don't have ability to even move to the Julia panel. Everything freezes. I'm trying to identify this, but please also try as well to find out which method/evaluation is so problematic.

**Comment by Datseris** [comment]
Yeah, complete memory leak, my Julia RAM usage was more than 7GB

**Comment by Datseris** [comment]
The memory leak was coming from Revise.jl. I've ported the docs to Makie.jl fully. Now everything works. THe docs compile in a couple of minutes. WIll merge once I see online compilation successful.

**Comment by kahaaga** [comment]
@Datseris What is the reason for writing `using TimeseriesSurrogates.StatsBase` instead of `using StatsBase`?

**Pull request merged**
